name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Upload files to Hostinger
        run: |
          rsync -avz --delete-after \
          -e "ssh -o StrictHostKeyChecking=no -p 65002" \
          ./ u118130549@154.41.233.109://home/u118130549/domains/wheels2deals.com/public_html

      - name: Create symbolic link
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u118130549@154.41.233.109 '
          cd /home/u118130549/domains/wheels2deals.com/public_html &&
          php artisan storage:link &&
          if [ ! -L public/storage ]; then
            ln -s ../storage/app/public public/storage
          fi
          '

      - name: Clear cache and optimize
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u118130549@154.41.233.109 '
          cd /home/u118130549/domains/wheels2deals.com/public_html &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan view:cache
